frams_path: "../external/Framsticks55"
frams_lib: null
sim_file: "eval-allcriteria.sim;deterministic.sim;sample-period-2.sim;only-body.sim"
opt_criteria:
  - "vertpos"

pop_size: 140
generations: 300
tournament_size: 4
p_mut: 0.9
p_xov: 0.0
hof_size: 1

genformat: "0"
initial_genotype: null

max_numparts: 15
max_numjoints: 15
max_numneurons: null
max_numconnections: null
max_numgenochars: null

result_filepath: "../results/sampled_best_individuals.jsonl"