# Konfiguracja autoenkodera
in_channels: 5
max_nodes: 15
#latent_dim: 16 # 3, 10, 15
latent_dim: 3
learning_rate: 0.01

encoder_conv_channels:
  - 16
  - 32

encoder_dense_features:
  - 128
  - 64

decoder_a_hidden_dims:
  - 64
  - 128

decoder_x_conv_channels:
  - 32
  - 16

decoder_x_dense_features:
  - 64
  - 128

weight_a: 500.0
kl_weight: 0.007

count_valid: true

locality_loss_type: "fitness" # 'fitness', 'parts_num' , 'similarity'
locality_loss_method: "spearman" # 'pearson', 'spearman'
locality_loss_lambda_val: 1.0
save_dir: "./checkpoints"