encoder_conv_channels:
  - 16
  - 32

encoder_dense_features:
  - 128
  - 64

decoder_a_hidden_dims:
  - 64
  - 128


# Decoder X
decoder_x_dense_features:
  - 64
  - 128

decoder_x_conv_channels:
  - 16

decoder_x_initial_channels: 32